### ISSUE TITLE
About the format of Image rendering

### ISSUE THREAD

**Issue by powenlo** [TonythePlaneswalker/pcn#10]
Hello, 
I would like to ask a quick question about image rendering. From README .md, the instruction is as follows:

- Create a model list. Each line of the model list should be in the format `[synset_id]/[model_id]`.
- Run `blender -b -P render_depth.py [ShapeNet directory] [model list] [output directory] [num scans per model]` to render the depth images. The images will be stored in OpenEXR format. 

However, I am quite confused about the format of the 'model list' and the 'ShapeNet directory'. Would you mind providing me with an easy example to show how it really looks like? Thanks a lot.

**Comment by maxjaritz** [comment]
A look into data_util.py helps. 
```
[ShapeNet directory] = /datasets/ShapeNetCore.v1
[model list] = model_list.txt
[num scans per model] = 8
```
The model_list.txt should contain:
```
02958343/1c9725db9005eda1aaa354fd606bff0
02958343/441d0b3f687e3721fed6082009db27d
```

@TonythePlaneswalker 
In ShapeNetCore.v1, there are a total of 7497 elements for the car class (02958343). In your train.lmdb for car there are 5677 * 8 views and in the valid.lmdb there are 100 * 1 view. Why didn't you use all elements for training?

**Comment by TonythePlaneswalker** [comment]
I remember encountering some errors while loading some of the car models for sampling/rendering. Maybe it's fixed now with the Blender rendering script (I switched to Blender later in the project). You can try using all the models for training.
