### ISSUE TITLE
Ground truth for training the model with my own dataset

### ISSUE THREAD

**Issue by powenlo** [TonythePlaneswalker/pcn#11]
Thanks for your nice work. 

I would like to train the model by my own dataset, however, I am still confused on the ground truth of the input data. From lmdb_writer.py, I found that only a single complete point cloud will be read while num_scan (e.g. 8) partial point cloud will be read. Under this circumstance, if I understand correctly, partial point cloud in different viewing angles will be completed using the same ground truth. Normally, during training, different input should refer to their own corresponding output, right? My question is that why we don't need to do the point cloud registration to align the completed point cloud with the partial point cloud first. 

Look forward to hearing from you.

**Comment by TonythePlaneswalker** [comment]
Good question. This work assumes the partial point clouds are aligned in a canonical coordinates (you can think of them being "registered"). Specifically, if the partial point clouds are created from depth scans, they are transformed into the world coordinates (coordinates of the original CAD model). Thus, partial point clouds from different views should correspond to the same complete point clouds.

That being said, you can still train the model using unaligned point clouds. As the network is learning a direct mapping via a joint feature space, it does not require the input and the output to correspond.

**Comment by powenlo** [comment]
Thanks a lot. One last question. Do you transform from partial to complete point cloud or from the complete to partial? I guess it should be from the partial to complete point cloud, right? Since in the program, you can only read one ground truth image per object.

**Comment by TonythePlaneswalker** [comment]
That is correct. [This line](https://github.com/TonythePlaneswalker/pcn/blob/47c27a2160f931c46767a788e95c3c4679abae4c/render/process_exr.py#L29) transforms partial point clouds to align with the ground truth.
