### ISSUE TITLE
Where is the coarse ground truth as indicated in the paper ?

### ISSUE THREAD

**Issue by iSarmad** [TonythePlaneswalker/pcn#15]
In your paper, figure 2 indicates that you used coarse ground truth (less than 16384 points) to calculate CD/ EMD with the Y_coarse. But in the code, I see that you used the Complete ground truth i.e. 16384 points for calculating chamfer distance with both Y_coarse and Y_fine. Am I missing something?

**Comment by TonythePlaneswalker** [comment]
The coarse ground truth is created by [subsampling the detailed ground truth on the fly](https://github.com/TonythePlaneswalker/pcn/blob/47c27a2160f931c46767a788e95c3c4679abae4c/models/pcn_emd.py#L56).

**Comment by iSarmad** [comment]
Thanks for your reply, But in case of pcn_cd,[ you are using fine ground truth instead of a coarse one](https://github.com/TonythePlaneswalker/pcn/blob/47c27a2160f931c46767a788e95c3c4679abae4c/models/pcn_cd.py#L53).
But I am guessing the calculation of chamfer distance is very efficient so it doesn't matter.
