### ISSUE TITLE
Memory will keep increasing?

### ISSUE THREAD

**Issue by whyccny** [TonythePlaneswalker/pcn#18]
@TonythePlaneswalker Hello, when I run the code, the network could be successfully tained. However, during the training process, the memory of my computer keep increasing all the time and normally until 7th epoch, my computer will crash. Do you have any idea of this situation? 
![1](https://user-images.githubusercontent.com/31809601/51782423-f4f0aa00-20f5-11e9-8c73-e8eb97e4d15a.png)

**Comment by whyccny** [comment]
@TonythePlaneswalker This is the initial memory,  after 7 epochs, it will become 100%

**Comment by TonythePlaneswalker** [comment]
Tensorpack will cache data in memory to accelerate data loading. If your computer doesn't have a lot of memory, try lowering the numbers (e.g. `buffer_size`, `nr_prefetch`) in `data_util.py`.
