### ISSUE TITLE
vtkOBJReader in sample.cpp not reading the whole mesh 

### ISSUE THREAD

**Issue by Colin97** [TonythePlaneswalker/pcn#20]
http://vtk.1045678.n5.nabble.com/vtkOBJReader-not-reading-the-whole-mesh-td5745864.html

**Comment by Colin97** [comment]
mesh_sampling.cpp

**Comment by TonythePlaneswalker** [comment]
Yes. There is a problem with vtkOBJReader while reading some ShapeNet models where parts of the model has tcoords/normals and other parts don't. I don't know if they have fixed that in the latest version. I solved this issue by adding the following code after line 956 in `vtkOBJReader.cxx` and rebuild VTK.
```
// Here we turn off texturing and/or normals
if (n_tcoord_pts == 0)
{
  hasTCoords = false;
}
if (n_normal_pts == 0)
{
  hasNormals = false;
}
```

**Comment by gillbam** [comment]
> Yes. There is a problem with vtkOBJReader while reading some ShapeNet models where parts of the model has tcoords/normals and other parts don't. I don't know if they have fixed that in the latest version. I solved this issue by adding the following code after line 956 in `vtkOBJReader.cxx` and rebuild VTK.
> 
> ```
> // Here we turn off texturing and/or normals
> if (n_tcoord_pts == 0)
> {
>   hasTCoords = false;
> }
> if (n_normal_pts == 0)
> {
>   hasNormals = false;
> }
> ```

I'm using VTK 8.2.0, this code is useful, however, it shuld locate after line  858.

**Comment by haomengz** [comment]
@gillbam Hi, I am also using VTK 8.2.0 and rebuild it after adding the code above, however I am still getting errors mentioned in #40 . Do you have that issue?

**Comment by haomengz** [comment]
@gillbam NVM I have fixed that. Thanks for the direction of VTK 8.2.0.
