### ISSUE TITLE
Training hangs

### ISSUE THREAD

**Issue by LiZimo** [TonythePlaneswalker/pcn#3]
Training will hang indefinitely on the first backprop command: 
```
print('backpropping a step')
_, loss, summary = sess.run([train_op, model.loss, train_summary],
                                    feed_dict={is_training_pl: True})
print('finished backpropping a step')
```
second print statement doesn't occur, even after a long time.  
When I examined further, in fact simply running:

`loss = sess.run([model.loss], feed_dict={is_training_pl: True})`

will also hang. Any idea of why this could be happening?  I set batch size to 1, and checking the GPUs, they are not being used.  

I am also getting the following error in the error log:
`pyarrow.lib.ArrowIOError: Expected to be able to read 196608 bytes for message body, got 196576`,

but the script continues after this error is given, so I'm not sure it is relevant.

**Comment by TonythePlaneswalker** [comment]
The lmdb files in the Google drive were created with an older version of pyarrow, which seems to be incompatible with the newer version. I have updated those files. If you download the new training and validation files this issue should be resolved.
