### ISSUE TITLE
Demo using ModelNet40

### ISSUE THREAD

**Issue by sheshappanavar** [TonythePlaneswalker/pcn#30]
Hi,

I tried to demo using a point cloud object(chair) from ModelNet40. 
However, the PCN shape completion did not work.

![chairmodelnet40](https://user-images.githubusercontent.com/2320460/63474688-0578c100-c448-11e9-8124-9e1ed4b24f31.png)

Please let me know if there are some concrete steps to prepare the datasets which can work with the pre-trained models provided in this repository.

Thank you

**Comment by TonythePlaneswalker** [comment]
The point clouds in ShapeNet, which are used to train the provided model, are mean-centered and normalized within the unit sphere. Note that this normalization applies to the complete point cloud or mesh model rather than the partial one.

**Comment by mactavish10** [comment]
Did you find a solution for this? I tried mean centering and normalizing the point cloud, yet I am getting the same kind of results for point clouds that are not a part of ShapeNet. @wentaoyuan @sheshappanavar

**Comment by m-kafiyan** [comment]
@wentaoyuan can you share the part of code doing mean-centering and normalization? I created my data (it is not from shapenet) based on the codes provided in sample and render folders but I think there is an scaling problem (not the scale of the points). or can you provide more information about the shapenet dataset that I change my custom data to those features.
