### ISSUE TITLE
Generate train.lmdb &valid.lmdb from data.mdb lock.mdb

### ISSUE THREAD

**Issue by bamboosdu** [TonythePlaneswalker/pcn#33]
Hi,
Thanks for the great work.
I met some troubles when I use the "lmdb_writer.py". While it do works, the lmdb_writer generates the files like below:
`
-lmdb_output
|---data.mdb
|---lock.mdb
`
I am confused about how to generate train.Imdb and valid.lmdb from data.mdb and lock.mdb.
Thanks for your attention.

**Comment by sheshappanavar** [comment]
@bamboosdu any updates on this? I am not sure why this issue was closed.
Please let us know if you found a way to generate train.lmdb and valid.lmdb
