### ISSUE TITLE
Fail to run render/process_exr.py

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [TonythePlaneswalker/pcn#35]
Hello~ Thanks for your great work and I m trying to generate some partial examples on my own.

I failed to run process_exr.py because I can't import both 'Imath' and 'OpenEXR'. I install them both in the common way(pip install) which leads to the disabled result. Can you please give me some tips about how to install them correctly?

P.S.
I find 'Imath' from: https://pypi.org/project/imath/#modal-close, which is released firstly in Mar,2019 but your code is completed in May,2018. So am I find a wrong lib?

My system is as below:
ubuntu 16.04
python 3.6.8

Looking for your reply,
Best and regards.

**Comment by SkyeFromKindergarten** [comment]
Solved :-)

**Comment by SarahChane98** [comment]
> Solved :-)

Hi @SkyeFromKindergarten may I know how you solved the problem? I installed OpenEXR by following instructions in their repo. However, when I ran process_exr.py it still showed "No module named Imath". Any tips on installation? Thank you!:)

**Comment by gillbam** [comment]
I'm sure you have solved the issue. Just for others: install openexr 1.3.2 by using conda
