### ISSUE TITLE
Instructions on how to serialize data?

### ISSUE THREAD

**Issue by LiZimo** [TonythePlaneswalker/pcn#4]
Not really an issue with the code, but I wanted to use this architecture to train with my own data. In the README, there is mention of serializing the data using "lmdb_writer.py", but the file is not in the directory.

Can you provide instructions on how to serialize point-cloud data into the expected format in the lmdb? Thanks.

**Comment by TonythePlaneswalker** [comment]
The file is added in the latest commit. The instructions are in README. Once you have the partial and complete point clouds, serializing them into lmdb is pretty easy. Feel free to change the script to fit your folder structure.
