### ISSUE TITLE
sample data error occured

### ISSUE THREAD

**Issue by Lilac-Lee** [TonythePlaneswalker/pcn#5]
Hi, Wentao,
Thanks for your excellent work.
When I tried to use your sample file to do point sampling, and used the default number of samples and the leaf size, it got this error:
`Convert ../data/lexus_hs.obj to a point cloud using uniform sampling.
[pcl::VoxelGrid::applyFilter] Leaf size is too small for the input dataset. Integer indices would overflow.XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:13.0"
      after 48 requests (48 known processed) with 19 events remaining.
`
I'm wondering could you tell me how to choose the number of samples of the leaf size properly?
Thanks.

**Comment by Lilac-Lee** [comment]
another thought, I reckon I know that the fatal IO error 11 is due to lack of the GUI, but still want to know the intuition to choose the leaf size.

**Comment by TonythePlaneswalker** [comment]
The number of samples and leaf size depend on the size of your model. For ShapeNet models, which are normalized into a unit cube, a leaf size of 0.02 with 10000 points works fine. Note that voxel filtering is not necessary. You can also turn it off with -no_vox_filter.
