### ISSUE TITLE
Importing error: pc_distance.tf_nndistance

### ISSUE THREAD

**Issue by StatML** [TonythePlaneswalker/pcn#7]
Hi, I am using Ubuntu 16.04, Python 3.5, CUDA 9.2, TensorFlow 1.10. When I try to import tf_nndistance, I met the following issues. Does anyone know how to fix it? Thanks!

> In [1]: import pc_distance.tf_nndistance
> ---------------------------------------------------------------------------
> NotFoundError                             Traceback (most recent call last)
> <ipython-input-1-06f0b6af2e4a> in <module>()
> ----> 1 import pc_distance.tf_nndistance
> 
> ~/pcn/pc_distance/tf_nndistance.py in <module>()
>       3 from tensorflow.python.framework import ops
>       4 BASE_DIR = os.path.dirname(os.path.abspath(__file__))
> ----> 5 nn_distance_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_nndistance_so.so'))
>       6 
>       7 def nn_distance(xyz1,xyz2):
> 
> /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
>      54     RuntimeError: when unable to load the library or get the python wrappers.
>      55   """
> ---> 56   lib_handle = py_tf.TF_LoadLibrary(library_filename)
>      57 
>      58   op_list_str = py_tf.TF_GetOpList(lib_handle)
> 
> NotFoundError: /home/xxx/pcn/pc_distance/tf_nndistance_so.so: undefined symbol: _Z24NmDistanceKernelLauncheriiPKfiS0_PfPiS1_S2_

**Comment by TonythePlaneswalker** [comment]
The code is tested under CUDA 8.0 and TF 1.4. You may need to modify `pc_distance/makefile` to make it work under TF 1.10. You can refer to the official TF [documentation](https://www.tensorflow.org/extend/adding_an_op) for this.
