### ISSUE TITLE
Paper Results

### ISSUE THREAD

**Issue by lynetcha** [TonythePlaneswalker/pcn#8]
The paper reports a mean CD of 0.009636 in Table 4 of the supplementary materials. This seems like a pretty high error given the quality of the results. I ran the network with a different experimental setup and obtained a value closer to 0.00096 (~1/10th of the number above). Could there be a factor of 10 missing in the reported results?

**Comment by TonythePlaneswalker** [comment]
I don't think so. Did you use the provided evaluation code? Under what setup did you train the model?

Note that the reported number is the average distance, not average distance squared.

**Comment by lynetcha** [comment]
Thanks for the clarification. I was using the original chamfer loss from [Point Set Generation](https://github.com/fanhqme/PointSetGeneration/tree/master/depthestimate). I just saw that you made some modifications to it. Will try your loss instead.

**Comment by lynetcha** [comment]
I am trying to run your code but it takes about 0.55s per batch on a 1080ti. Dataloading doesn't seem to be the issue as judged by setting test_speed=True. Any reason why this might be so slow?

**Comment by TonythePlaneswalker** [comment]
I think it’s mainly the backward pass that’s slow because I didn’t use any optimized implementation for the folding operation.
