### ISSUE TITLE
Running make under pc_distance

### ISSUE THREAD

**Issue by powenlo** [TonythePlaneswalker/pcn#9]
Hello, I would like to enquiry something about the makefile in pc_distance. When I run the "make" under pc_distance. There is an error which states that:

Circular tf_nndistance.cu <- tf_nndistance.cu.o dependency dropped.
make: Circular tf_approxmatch.cu <- tf_approxmatch.cu.o dependency dropped.
make: Nothing to be done for 'all'.

Can anyone tell me what is going on here? Any suggestion is welcome.

**Comment by TonythePlaneswalker** [comment]
This is not an error. There is nothing to be done because I added the built .so files to the repo to avoid compilation issues caused by different versions of tensorflow.
